# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title etimate possion process.
#' @description we can get in in R.
#' @param lambda the parameter of the exponential distribution.
#' @return a result \code{n}
#' @useDynLib SC19089
#' @examples
#' \dontrun{
#' xtC(100,1)
#' }
#' @export
xtC <- function(N, lambda) {
    .Call('_SC19089_xtC', PACKAGE = 'SC19089', N, lambda)
}

